.TH "ants.py" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBants\&.Ant\fP"
.br
.ti -1c
.RI "class \fBants\&.WorkerAnt\fP"
.br
.ti -1c
.RI "class \fBants\&.QueenAnt\fP"
.br
.ti -1c
.RI "class \fBants\&.SoldierAnt\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBants\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
