.TH "ants.SoldierAnt" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants.SoldierAnt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBants\&.Ant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBget_enemy_ant_nearby\fP"
.br
.ti -1c
.RI "def \fBattack\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Ants that produces offsprings and populates the colony
.fi
.PP
 
.PP
Definition at line 342 of file ants\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ants\&.SoldierAnt\&.__init__ (self, world, image, direction, location, nest)"

.PP
.nf
Tasks assigned:
    - Guard nest
    - Return home
Default task:
    - Guard nest

.fi
.PP
 
.PP
Definition at line 344 of file ants\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def ants\&.SoldierAnt\&.attack (self, ant)"

.PP
Definition at line 366 of file ants\&.py\&.
.SS "def ants\&.SoldierAnt\&.get_enemy_ant_nearby (self)"

.PP
.nf
Returns one enemy ant nearby at random

.fi
.PP
 
.PP
Definition at line 357 of file ants\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
