.TH "ants" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnt\fP"
.br
.ti -1c
.RI "class \fBWorkerAnt\fP"
.br
.ti -1c
.RI "class \fBQueenAnt\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
