.TH "ants.QueenAnt" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants.QueenAnt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBants\&.Ant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Ants that produces offsprings and populates the colony
.fi
.PP
 
.PP
Definition at line 223 of file ants\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ants\&.QueenAnt\&.__init__ (self, world, image, direction, location)"

.PP
.nf
Tasks assigned:
    - HaveFood
    - Produce offsprings
Default task:
    - Have Food

.fi
.PP
 
.PP
Definition at line 225 of file ants\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
