.TH "ants.WorkerAnt" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants.WorkerAnt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBants\&.Ant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBlocate_food_scent_nearby\fP"
.br
.ti -1c
.RI "def \fBrank_by_food_scent\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Ants that explores for foodsource and collects food

.fi
.PP
 
.PP
Definition at line 260 of file ants\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ants\&.WorkerAnt\&.__init__ (self, world, image, direction, location, nest)"

.PP
.nf
Tasks assigned:
    - Explore
    - TakeFood
    - DropFood
    - FollowFoodTrail
    - FollowHomeTrail
Default task:
    - Explore

.fi
.PP
 
.PP
Definition at line 264 of file ants\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def ants\&.WorkerAnt\&.locate_food_scent_nearby (self)"

.PP
.nf
Scan the 5 directions near the direction of the ant for food scent and
return one random direction
return None if not found

.fi
.PP
 
.PP
Definition at line 283 of file ants\&.py\&.
.SS "def ants\&.WorkerAnt\&.rank_by_food_scent (self)"

.PP
.nf
Scan the 5 directions near the direction of the ant for food scent and
return the direction with the strongest scent
return None if not found

.fi
.PP
 
.PP
Definition at line 303 of file ants\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
