.TH "ants.WorkerAnt" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants.WorkerAnt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBants\&.Ant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Ants that explores for foodsource and collects food
.fi
.PP
 
.PP
Definition at line 201 of file ants\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ants\&.WorkerAnt\&.__init__ (self, world, image, direction, location)"

.PP
.nf
Tasks assigned:
    - Explore
    - TakeFood
    - DropFood
    - FollowFoodTrail
    - FollowHomeTrail
Default task:
    - Explore

.fi
.PP
 
.PP
Definition at line 203 of file ants\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
