.TH "ants.Ant" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ants.Ant \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdisplay\&.Entity\fP\&.
.PP
Inherited by \fBants\&.QueenAnt\fP, \fBants\&.SoldierAnt\fP, and \fBants\&.WorkerAnt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBget_location\fP"
.br
.ti -1c
.RI "def \fBneighbour\fP"
.br
.ti -1c
.RI "def \fBmove\fP"
.br
.ti -1c
.RI "def \fBrandom_move\fP"
.br
.ti -1c
.RI "def \fBreduce_home_scent_strength\fP"
.br
.ti -1c
.RI "def \fBreduce_food_scent_strength\fP"
.br
.ti -1c
.RI "def \fBturn\fP"
.br
.ti -1c
.RI "def \fBrender\fP"
.br
.ti -1c
.RI "def \fBget_nest_id\fP"
.br
.ti -1c
.RI "def \fBhere\fP"
.br
.ti -1c
.RI "def \fBbehind\fP"
.br
.ti -1c
.RI "def \fBahead\fP"
.br
.ti -1c
.RI "def \fBahead_left\fP"
.br
.ti -1c
.RI "def \fBahead_right\fP"
.br
.ti -1c
.RI "def \fBlocate_food_nearby\fP"
.br
.ti -1c
.RI "def \fBis_enemy\fP"
.br
.RI "\fIReturns true if the ant passed is an enemy\&. \fP"
.ti -1c
.RI "def \fBlocate_home_nearby\fP"
.br
.ti -1c
.RI "def \fBlocate_home_scent_nearby\fP"
.br
.ti -1c
.RI "def \fBrank_by_home_scent\fP"
.br
.ti -1c
.RI "def \fBdrop_food\fP"
.br
.ti -1c
.RI "def \fBtake_food\fP"
.br
.RI "\fIcarry half the food and increase health by half the amount \fP"
.ti -1c
.RI "def \fBhas_food\fP"
.br
.ti -1c
.RI "def \fBset_food_scent_strength\fP"
.br
.ti -1c
.RI "def \fBset_home_scent_strength\fP"
.br
.ti -1c
.RI "def \fBreduce_health\fP"
.br
.RI "\fIReduces the health of the ant\&. \fP"
.ti -1c
.RI "def \fBis_dead\fP"
.br
.ti -1c
.RI "def \fBis_alive\fP"
.br
.ti -1c
.RI "def \fBis_hungry\fP"
.br
.ti -1c
.RI "def \fB__nonzero__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBworld\fP"
.br
.ti -1c
.RI "\fBimage\fP"
.br
.ti -1c
.RI "\fBnest\fP"
.br
.ti -1c
.RI "\fBdirection\fP"
.br
.ti -1c
.RI "\fBlocation\fP"
.br
.ti -1c
.RI "\fBfood\fP"
.br
.ti -1c
.RI "\fBhealth\fP"
.br
.ti -1c
.RI "\fBfood_scent_strength\fP"
.br
.ti -1c
.RI "\fBhome_scent_strength\fP"
.br
.ti -1c
.RI "\fBtask_manager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A virtual base class for Ants

.fi
.PP
 
.PP
Definition at line 8 of file ants\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ants\&.Ant\&.__init__ (self, world, image, direction, location, nest)"

.PP
Definition at line 12 of file ants\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def ants\&.Ant\&.__nonzero__ (self)"

.PP
Definition at line 256 of file ants\&.py\&.
.SS "def ants\&.Ant\&.ahead (self)"

.PP
.nf
The cell just ahead

.fi
.PP
 
.PP
Definition at line 117 of file ants\&.py\&.
.SS "def ants\&.Ant\&.ahead_left (self)"

.PP
.nf
The cell just ahead-left

.fi
.PP
 
.PP
Definition at line 123 of file ants\&.py\&.
.SS "def ants\&.Ant\&.ahead_right (self)"

.PP
.nf
The cell just ahead-right

.fi
.PP
 
.PP
Definition at line 129 of file ants\&.py\&.
.SS "def ants\&.Ant\&.behind (self)"

.PP
.nf
The cell just behind

.fi
.PP
 
.PP
Definition at line 111 of file ants\&.py\&.
.SS "def ants\&.Ant\&.drop_food (self)"

.PP
.nf
Set food to zero
Update the food values of the home cell it reached

.fi
.PP
 
.PP
Definition at line 214 of file ants\&.py\&.
.SS "def ants\&.Ant\&.get_location (self)"

.PP
Definition at line 26 of file ants\&.py\&.
.SS "def ants\&.Ant\&.get_nest_id (self)"

.PP
.nf
Returns the id of the nest it belongs to

.fi
.PP
 
.PP
Definition at line 99 of file ants\&.py\&.
.SS "def ants\&.Ant\&.has_food (self)"

.PP
.nf
Checks if the ant has food_scent

.fi
.PP
 
.PP
Definition at line 230 of file ants\&.py\&.
.SS "def ants\&.Ant\&.here (self)"

.PP
.nf
The cell it is standing on

.fi
.PP
 
.PP
Definition at line 105 of file ants\&.py\&.
.SS "def ants\&.Ant\&.is_alive (self)"

.PP
Definition at line 250 of file ants\&.py\&.
.SS "def ants\&.Ant\&.is_dead (self)"

.PP
Definition at line 247 of file ants\&.py\&.
.SS "def ants\&.Ant\&.is_enemy (self, ant)"

.PP
Returns true if the ant passed is an enemy\&. 
.PP
\fBParameters:\fP
.RS 4
\fIant\fP The other ant 
.RE
.PP

.PP
Definition at line 155 of file ants\&.py\&.
.SS "def ants\&.Ant\&.is_hungry (self)"

.PP
Definition at line 253 of file ants\&.py\&.
.SS "def ants\&.Ant\&.locate_food_nearby (self)"

.PP
.nf
Locate all sources nearby and return any one randomly
return None if no food source is found

.fi
.PP
 
.PP
Definition at line 135 of file ants\&.py\&.
.SS "def ants\&.Ant\&.locate_home_nearby (self)"

.PP
.nf
Locate home cell nearby and return any one randomly
return None if not found

.fi
.PP
 
.PP
Definition at line 158 of file ants\&.py\&.
.SS "def ants\&.Ant\&.locate_home_scent_nearby (self)"

.PP
.nf
Scan the 5 directions near the direction of the ant for home scent and
return one random direction
return None if not found

.fi
.PP
 
.PP
Definition at line 176 of file ants\&.py\&.
.SS "def ants\&.Ant\&.move (self)"

.PP
.nf
Moves the ant by a unit if the next cell is empty,
otherwise turn by an unit
It also leaves a scent trail,
remove the ant from its old cell, and
update the current cell ant with itself

.fi
.PP
 
.PP
Definition at line 38 of file ants\&.py\&.
.SS "def ants\&.Ant\&.neighbour (self, direction)"

.PP
.nf
Returns location of neighbouring cell in a direction 
relative to the ant direction

.fi
.PP
 
.PP
Definition at line 29 of file ants\&.py\&.
.SS "def ants\&.Ant\&.random_move (self)"

.PP
.nf
Ant makes a move forward or turns randomly

.fi
.PP
 
.PP
Definition at line 60 of file ants\&.py\&.
.SS "def ants\&.Ant\&.rank_by_home_scent (self)"

.PP
.nf
Scan the 5 directions near the direction of the ant for home scent and
return the direction with the strongest scent
return None if not found

.fi
.PP
 
.PP
Definition at line 196 of file ants\&.py\&.
.SS "def ants\&.Ant\&.reduce_food_scent_strength (self, amt = \fC1\fP)"

.PP
.nf
Reduce food scent by 'amt'

.fi
.PP
 
.PP
Definition at line 76 of file ants\&.py\&.
.SS "def ants\&.Ant\&.reduce_health (self, amt)"

.PP
Reduces the health of the ant\&. 
.PP
\fBParameters:\fP
.RS 4
\fIamt\fP The amount of health to reduce 
.RE
.PP

.PP
Definition at line 244 of file ants\&.py\&.
.SS "def ants\&.Ant\&.reduce_home_scent_strength (self, amt = \fC1\fP)"

.PP
.nf
Reduce home scent by 'amt'

.fi
.PP
 
.PP
Definition at line 69 of file ants\&.py\&.
.SS "def ants\&.Ant\&.render (self)"

.PP
.nf
Render itself

.fi
.PP
 
.PP
Definition at line 89 of file ants\&.py\&.
.SS "def ants\&.Ant\&.set_food_scent_strength (self, strength)"

.PP
Definition at line 236 of file ants\&.py\&.
.SS "def ants\&.Ant\&.set_home_scent_strength (self, strength)"

.PP
Definition at line 239 of file ants\&.py\&.
.SS "def ants\&.Ant\&.take_food (self, amt)"

.PP
carry half the food and increase health by half the amount 
.PP
\fBParameters:\fP
.RS 4
\fIamt\fP The amount of food 
.RE
.PP

.PP
Definition at line 226 of file ants\&.py\&.
.SS "def ants\&.Ant\&.turn (self, n)"

.PP
.nf
Changes direction n times

.fi
.PP
 
.PP
Definition at line 83 of file ants\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "ants\&.Ant\&.direction"

.PP
Definition at line 17 of file ants\&.py\&.
.SS "ants\&.Ant\&.food"

.PP
Definition at line 19 of file ants\&.py\&.
.SS "ants\&.Ant\&.food_scent_strength"

.PP
Definition at line 21 of file ants\&.py\&.
.SS "ants\&.Ant\&.health"

.PP
Definition at line 20 of file ants\&.py\&.
.SS "ants\&.Ant\&.home_scent_strength"

.PP
Definition at line 22 of file ants\&.py\&.
.SS "ants\&.Ant\&.image"

.PP
Definition at line 15 of file ants\&.py\&.
.SS "ants\&.Ant\&.location"

.PP
Definition at line 18 of file ants\&.py\&.
.SS "ants\&.Ant\&.nest"

.PP
Definition at line 16 of file ants\&.py\&.
.SS "ants\&.Ant\&.task_manager"

.PP
Definition at line 24 of file ants\&.py\&.
.SS "ants\&.Ant\&.world"

.PP
Definition at line 14 of file ants\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
