.TH "constants" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBDIRECTIONS\fP"
.br
.ti -1c
.RI "int \fBWIDTH\fP = 80"
.br
.ti -1c
.RI "int \fBHEIGHT\fP = 60"
.br
.ti -1c
.RI "tuple \fBWHITE\fP = (255,255,255)"
.br
.ti -1c
.RI "tuple \fBGREEN\fP = (0,255,20)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple constants\&.DIRECTIONS"
\fBInitial value:\fP
.PP
.nf
1 = ((1,0), (1,1), (0,1), (-1,1),
2     (-1,0), (-1,-1), (0,-1), (1,-1))
.fi
.PP
Definition at line 1 of file constants\&.py\&.
.SS "tuple constants\&.GREEN = (0,255,20)"

.PP
Definition at line 6 of file constants\&.py\&.
.SS "int constants\&.HEIGHT = 60"

.PP
Definition at line 4 of file constants\&.py\&.
.SS "tuple constants\&.WHITE = (255,255,255)"

.PP
Definition at line 5 of file constants\&.py\&.
.SS "int constants\&.WIDTH = 80"

.PP
Definition at line 3 of file constants\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
