.TH "constants.py" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconstants\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBconstants\&.DIRECTIONS\fP"
.br
.ti -1c
.RI "int \fBconstants\&.WIDTH\fP = 80"
.br
.ti -1c
.RI "int \fBconstants\&.HEIGHT\fP = 60"
.br
.ti -1c
.RI "tuple \fBconstants\&.WHITE\fP = (255,255,255)"
.br
.ti -1c
.RI "tuple \fBconstants\&.GREEN\fP = (0,255,20)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
