.TH "main" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBsimulation\fP = \fBSimulation\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple main\&.simulation = \fBSimulation\fP()"

.PP
Definition at line 4 of file main\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
