.TH "task_manager.FollowFoodTrail" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.FollowFoodTrail \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtask_manager\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBstart_task\fP"
.br
.ti -1c
.RI "def \fBperform_task\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnew_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
docstring for FollowFoodTrail
.fi
.PP
 
.PP
Definition at line 153 of file task_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task_manager\&.FollowFoodTrail\&.__init__ (self, ant)"

.PP
Definition at line 155 of file task_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def task_manager\&.FollowFoodTrail\&.perform_task (self)"

.PP
.nf
if food is found take food_scent_strength
otherwise rank cells based on scent and follow it
if scent trail is lost, return to explore mode

.fi
.PP
 
.PP
Definition at line 161 of file task_manager\&.py\&.
.SS "def task_manager\&.FollowFoodTrail\&.start_task (self)"

.PP
Definition at line 158 of file task_manager\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "task_manager\&.FollowFoodTrail\&.new_task"

.PP
Definition at line 172 of file task_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
