.TH "task_manager.TakeFood" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.TakeFood \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtask_manager\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBperform_task\fP"
.br
.ti -1c
.RI "def \fBend_task\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnew_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Gathering Food Task
.fi
.PP
 
.PP
Definition at line 103 of file task_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task_manager\&.TakeFood\&.__init__ (self, ant)"

.PP
Definition at line 105 of file task_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def task_manager\&.TakeFood\&.end_task (self)"

.PP
.nf
Increase food_scent_strength
and reduce home_scent_strength
.fi
.PP
 
.PP
Definition at line 119 of file task_manager\&.py\&.
.SS "def task_manager\&.TakeFood\&.perform_task (self)"

.PP
.nf
Take food if available otherwise return to explore mode
.fi
.PP
 
.PP
Definition at line 108 of file task_manager\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "task_manager\&.TakeFood\&.new_task"

.PP
Definition at line 115 of file task_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
