.TH "task_manager.Explore" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.Explore \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtask_manager\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBperform_task\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnew_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Ant Exploring Task
.fi
.PP
 
.PP
Definition at line 56 of file task_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task_manager\&.Explore\&.__init__ (self, ant)"

.PP
Definition at line 58 of file task_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def task_manager\&.Explore\&.perform_task (self)"

.PP
.nf
 If ant has food - 
     find home nearby and drop food there, else
     find home scent nearby and switch to that task, else
     make a random move
 If ant is searching for food
     if food is found switch to take food task, else
     find a food scent trail, else
     avoid obstacles
     reverse direction if it finds home nearby
 Reduce it scent strength by an unit

.fi
.PP
 
.PP
Definition at line 61 of file task_manager\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "task_manager\&.Explore\&.new_task"

.PP
Definition at line 79 of file task_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
