.TH "task_manager" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTaskManager\fP"
.br
.ti -1c
.RI "class \fBTask\fP"
.br
.ti -1c
.RI "class \fBExplore\fP"
.br
.ti -1c
.RI "class \fBTakeFood\fP"
.br
.ti -1c
.RI "class \fBDropFood\fP"
.br
.ti -1c
.RI "class \fBFollowFoodTrail\fP"
.br
.ti -1c
.RI "class \fBFollowHomeTrail\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
