.TH "task_manager.GuardNest" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.GuardNest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtask_manager\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBstart_task\fP"
.br
.ti -1c
.RI "def \fBperform_task\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnew_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Guards the nest
If it sees an enemy ant it attacks it

.fi
.PP
 
.PP
Definition at line 293 of file task_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task_manager\&.GuardNest\&.__init__ (self, ant)"

.PP
Definition at line 298 of file task_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def task_manager\&.GuardNest\&.perform_task (self)"

.PP
.nf
Travel along the walls of the nest

.fi
.PP
 
.PP
Definition at line 305 of file task_manager\&.py\&.
.SS "def task_manager\&.GuardNest\&.start_task (self)"

.PP
Definition at line 301 of file task_manager\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "task_manager\&.GuardNest\&.new_task"

.PP
Definition at line 315 of file task_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
