.TH "task_manager.ReturnHome" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.ReturnHome \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtask_manager\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBstart_task\fP"
.br
.ti -1c
.RI "def \fBperform_task\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnew_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Return home if the ant is roaming outside

.fi
.PP
 
.PP
Definition at line 261 of file task_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task_manager\&.ReturnHome\&.__init__ (self, ant)"

.PP
Definition at line 265 of file task_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def task_manager\&.ReturnHome\&.perform_task (self)"

.PP
.nf
Follow home trail and return home

.fi
.PP
 
.PP
Definition at line 272 of file task_manager\&.py\&.
.SS "def task_manager\&.ReturnHome\&.start_task (self)"

.PP
Definition at line 268 of file task_manager\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "task_manager\&.ReturnHome\&.new_task"

.PP
Definition at line 283 of file task_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
