.TH "task_manager.py" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtask_manager\&.TaskManager\fP"
.br
.ti -1c
.RI "class \fBtask_manager\&.Task\fP"
.br
.ti -1c
.RI "class \fBtask_manager\&.Explore\fP"
.br
.ti -1c
.RI "class \fBtask_manager\&.TakeFood\fP"
.br
.ti -1c
.RI "class \fBtask_manager\&.DropFood\fP"
.br
.ti -1c
.RI "class \fBtask_manager\&.FollowFoodTrail\fP"
.br
.ti -1c
.RI "class \fBtask_manager\&.FollowHomeTrail\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtask_manager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
