.TH "task_manager.ProduceAnts" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_manager.ProduceAnts \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtask_manager\&.Task\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBperform_task\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnew_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Randomly produce new ants

.fi
.PP
 
.PP
Definition at line 322 of file task_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task_manager\&.ProduceAnts\&.__init__ (self, ant)"

.PP
Definition at line 326 of file task_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def task_manager\&.ProduceAnts\&.perform_task (self)"

.PP
.nf
randomly produce new ants
.fi
.PP
 
.PP
Definition at line 329 of file task_manager\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "task_manager\&.ProduceAnts\&.new_task"

.PP
Definition at line 332 of file task_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
