.TH "world.Nest" 3 "Sat May 3 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
world.Nest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdisplay\&.Entity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_image\fP"
.br
.ti -1c
.RI "def \fBmark_home\fP"
.br
.ti -1c
.RI "def \fBspawn_ants\fP"
.br
.ti -1c
.RI "def \fBadd_new_ant\fP"
.br
.ti -1c
.RI "def \fBadd_new_ant_randomly\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid\fP"
.br
.ti -1c
.RI "\fBsize\fP"
.br
.ti -1c
.RI "\fBworld\fP"
.br
.ti -1c
.RI "\fBant_count\fP"
.br
.ti -1c
.RI "\fBimage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Encapsulates a colony of ants

.fi
.PP
 
.PP
Definition at line 213 of file world\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def world\&.Nest\&.__init__ (self, world, id, size, location, ant_count)"

.PP
Definition at line 217 of file world\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def world\&.Nest\&.add_new_ant (self, ant_type)"

.PP
Definition at line 255 of file world\&.py\&.
.SS "def world\&.Nest\&.add_new_ant_randomly (self)"

.PP
Definition at line 263 of file world\&.py\&.
.SS "def world\&.Nest\&.mark_home (self)"

.PP
.nf
Converts the cell at its location to its nest

.fi
.PP
 
.PP
Definition at line 235 of file world\&.py\&.
.SS "def world\&.Nest\&.set_image (self)"

.PP
Definition at line 227 of file world\&.py\&.
.SS "def world\&.Nest\&.spawn_ants (self)"

.PP
.nf
Creates instances of ants and adds them into the world

.fi
.PP
 
.PP
Definition at line 247 of file world\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "world\&.Nest\&.ant_count"

.PP
Definition at line 221 of file world\&.py\&.
.SS "world\&.Nest\&.id"

.PP
Definition at line 218 of file world\&.py\&.
.SS "world\&.Nest\&.image"

.PP
Definition at line 231 of file world\&.py\&.
.SS "world\&.Nest\&.size"

.PP
Definition at line 219 of file world\&.py\&.
.SS "world\&.Nest\&.world"

.PP
Definition at line 220 of file world\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
