.TH "world" 3 "Wed Apr 9 2014" "Ant Colony" \" -*- nroff -*-
.ad l
.nh
.SH NAME
world \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCell\fP"
.br
.ti -1c
.RI "class \fBWorld\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Ant Colony from the source code\&.
